version: '3'

services:
  web-service:
    build:
      context: ./Symptom_Checker_Website
    volumes:
      - ./Symptom_Checker_Website:/app
    ports:
      - "800:800"
  lung-cancer-services:
      build:
        context: ./Classification_services/lung-cancer
      ports:
      - "5000:5000"
  # ml-flow-model:
  #   build:
  #     context: ./ML_flow
  #   volumes:
  #     - ./ML_flow:/app

  #   42-disease-services:
  #     build:
  #       context: ./Classification_service/42-disease
  #     volumes:
  #     - ./Classification_service/42-disease:/app