version: '3'

services:
  web-service:
    image: tpattra/symptom_checker-web-service
    ports:
      - "8000:8000"
  lung-cancer-services:
      image: tpattra/symptom_checker-lung-cancer-services
      ports:
      - "5000:5000"
  42-disease-services:
      image: tpattra/symptom_checker-42-disease-services
      ports:
      - "8080:8080"