channels:
- conda-forge
dependencies:
- python=3.8.10
- pip<=23.3.1
- pip:
  - mlflow==2.8.1
  - cloudpickle==2.2.1
  - numpy==1.22.1
  - packaging==23.2
  - psutil==5.9.6
  - scikit-learn==1.3.2
  - scipy==1.10.1
name: mlflow-env
